version: "3"

services:
#  the application
  lwhh-app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/opt/app/src
    environment:
      - PORT=3000
      - DATABASE=postgres://postgres:asd123@lwhh-postgres:5432/lwhh
      - CORS=yes
    depends_on:
      - lwhh-postgres
#  database server
  lwhh-postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=asd123
      - POSTGRES_DB=lwhh
    logging:
      driver: none

  lwhh-adminer:
    image: adminer
    ports:
      - 8080:8080